export type LocalFontFace = {
  family: string;
  source: string;
  format: "woff2" | "woff" | "truetype" | "opentype";
  weight: "400" | "700";
};

export const LOCAL_FONT_FACES: LocalFontFace[] = [
  { family: "Cherry Unicode", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/CherryUnicode/Cherry_Unicode.ttf", format: "truetype", weight: "400" },
  { family: "Gantgaw Regular", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Gantgaw/Gantgaw-Regular.ttf", format: "truetype", weight: "400" },
  { family: "Jasmine Unicode", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/JasmineUnicode/Jasmine_Unicode.ttf", format: "truetype", weight: "400" },
  { family: "KT 02", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/KT_Unicode/KT_02.ttf", format: "truetype", weight: "400" },
  { family: "KT 03", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/KT_Unicode/KT_03.ttf", format: "truetype", weight: "400" },
  { family: "Masterpiece Uni Round", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MasterpieceUniRound/MasterpieceUniRound.ttf", format: "truetype", weight: "400" },
  { family: "MON3Anonta1", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MON3_Anonta/MON3Anonta1.ttf", format: "truetype", weight: "400" },
  { family: "mm3 05 Jan 2011", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Myanmar3/mm3_05-Jan-2011.ttf", format: "truetype", weight: "400" },
  { family: "mm3h", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Myanmar3/mm3h.ttf", format: "truetype", weight: "400" },
  { family: "mm3 multi os", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Myanmar3/mm3-multi-os.ttf", format: "truetype", weight: "400" },
  { family: "mm3sh", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Myanmar3/mm3sh.ttf", format: "truetype", weight: "400" },
  { family: "MM3 Paoh", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Myanmar3_PaOh/MM3_Paoh.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Angoun", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarAngoun/MyanmarAngoun.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Black", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarBlack/MyanmarBlack.ttf", format: "truetype", weight: "400" },
  { family: "myanmarcensus", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarCensus/myanmarcensus.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Gant Gaw", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarGantGaw/MyanmarGantGaw.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Khway", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarKhway/MyanmarKhway.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Kuttar", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarKuttar/MyanmarKuttar.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Nayone", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarNayone/MyanmarNayone.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Njaun", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarNjaun/MyanmarNjaun.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Pa Oh One", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPaOhOne/MyanmarPaOhOne.ttf", format: "truetype", weight: "400" },
  { family: "MIUI Unicode", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPaOhRosemary/MIUI%20Unicode.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Pauklay", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPauklay/MyanmarPauklay.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Phetsot", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPhetsot/MyanmarPhetsot.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Pixel Smooth", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPixel/MyanmarPixelSmooth.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Pixel", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPixel/MyanmarPixel.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Ponenyet", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPonenyet/MyanmarPonenyet.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Punk", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarPunk/Myanmar_Punk.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Rosemarry", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarRosemarry/Myanmar_Rosemarry.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Sabae", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarSabae/MyanmarSabae.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Sagar", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarSagar/MyanmarSagar.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Sans Pro", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarSansPro/MyanmarSansPro.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Square Light", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarSquare/MyanmarSquareLight.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Square", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarSquare/MyanmarSquare.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Tagu", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarTagu/MyanmarTagu.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Taungyi", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarTaungyi/MyanmarTaungyi.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Text Melano", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarTextMelano/MyanmarTextMelano.ttf", format: "truetype", weight: "400" },
  { family: "mmrtextb", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarText/mmrtextb.ttf", format: "truetype", weight: "400" },
  { family: "mmrtext", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarText/mmrtext.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Thuriya", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarThuriya/MyanmarThuriya.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Thuriya volt", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarThuriya/MyanmarThuriya_volt.ttf", format: "truetype", weight: "400" },
  { family: "Myanmar Yinmar", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/MyanmarYinmar/MyanmarYinmar.ttf", format: "truetype", weight: "400" },
  { family: "Nam Khone Unicode", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Namkhon/NamKhoneUnicode.ttf", format: "truetype", weight: "400" },
  { family: "Namkhon Web pro", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Namkhon/Namkhon_Web_pro.ttf", format: "truetype", weight: "400" },
  { family: "NK Grand", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Namkhon/NK%20Grand.ttf", format: "truetype", weight: "400" },
  { family: "NK SSmart2", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Namkhon/NK_SSmart2.ttf", format: "truetype", weight: "400" },
  { family: "NK SSmart3", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Namkhon/NK_SSmart3.ttf", format: "truetype", weight: "400" },
  { family: "NK SSmart4", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Namkhon/NK_SSmart4.ttf", format: "truetype", weight: "400" },
  { family: "Notosan Myanmar UI Bold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/NotoSansMyanmar/Notosan%20Myanmar%20UI%20Bold.ttf", format: "truetype", weight: "700" },
  { family: "Noto Sans Myanmar Bold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/NotoSansMyanmar/NotoSansMyanmar-Bold.ttf", format: "truetype", weight: "700" },
  { family: "Noto Sans Myanmar Regular", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/NotoSansMyanmar/NotoSansMyanmar-Regular.ttf", format: "truetype", weight: "400" },
  { family: "Noto Sans Myanmar UI Bold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/NotoSansMyanmar/NotoSansMyanmarUI-Bold.ttf", format: "truetype", weight: "700" },
  { family: "Noto Sans Myanmar UI Regular", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/NotoSansMyanmar/NotoSansMyanmarUI-Regular.ttf", format: "truetype", weight: "400" },
  { family: "Padauk GhostтАЛ", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukGhost/PadaukGhost%D1%82%D0%90%D0%9B.ttf", format: "truetype", weight: "400" },
  { family: "Padauk Grand Pro v2", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukGrandPro/PadaukGrandPro%20v2.ttf", format: "truetype", weight: "400" },
  { family: "Padauk Kyaungchikote", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukKyaungchikote/Padauk%20Kyaungchikote.ttf", format: "truetype", weight: "400" },
  { family: "Padauk bold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Padauk/Padauk-bold.ttf", format: "truetype", weight: "700" },
  { family: "padauk bookbold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Padauk/padauk-bookbold.ttf", format: "truetype", weight: "700" },
  { family: "padauk book", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Padauk/padauk-book.ttf", format: "truetype", weight: "400" },
  { family: "Padauk", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Padauk/Padauk.ttf", format: "truetype", weight: "400" },
  { family: "Padauk Zawgyi", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Padauk/Padauk-Zawgyi.ttf", format: "truetype", weight: "400" },
  { family: "Padauk Sagar", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukSagar/PadaukSagar.ttf", format: "truetype", weight: "400" },
  { family: "Padauk Sgaw Bold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukSgaw/PadaukSgaw-Bold.ttf", format: "truetype", weight: "700" },
  { family: "Padauk Sgaw bookbold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukSgaw/PadaukSgaw-bookbold.ttf", format: "truetype", weight: "700" },
  { family: "Padauk Sgaw book", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukSgaw/PadaukSgaw-book.ttf", format: "truetype", weight: "400" },
  { family: "Padauk Sgaw", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PadaukSgaw/PadaukSgaw.ttf", format: "truetype", weight: "400" },
  { family: "Pang Long 2011feb7", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PangLong/PangLong_2011feb7.ttf", format: "truetype", weight: "400" },
  { family: "Paoh Dragon App", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/PaohDragonApp/PaohDragonApp.ttf", format: "truetype", weight: "400" },
  { family: "Parabaik20080421", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Parabaik/Parabaik20080421.ttf", format: "truetype", weight: "400" },
  { family: "Parabaik UTN11 3", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Parabaik/Parabaik_UTN11-3.ttf", format: "truetype", weight: "400" },
  { family: "pyidaungsu 1.2", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Pyidaungsu/pyidaungsu-1.2.ttf", format: "truetype", weight: "400" },
  { family: "pyidaungsu 1.3", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Pyidaungsu/pyidaungsu-1.3.ttf", format: "truetype", weight: "400" },
  { family: "pyidaungsu", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Pyidaungsu/pyidaungsu.ttf", format: "truetype", weight: "400" },
  { family: "Samsung Myanmar", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/SamsungMyanmar/Samsung%20Myanmar.ttf", format: "truetype", weight: "400" },
  { family: "Shan Unicode", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/ShanUnicode/Shan%20Unicode.ttf", format: "truetype", weight: "400" },
  { family: "Than Lwin", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Thanlwin/ThanLwin.ttf", format: "truetype", weight: "400" },
  { family: "Thar Lon", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Tharlon/TharLon.ttf", format: "truetype", weight: "400" },
  { family: "Win Uni Innwa", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/WinUniInnwa/WinUniInnwa.ttf", format: "truetype", weight: "400" },
  { family: "Yoe Yar One Bold", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/YoeYarOne/YoeYar-One%20Bold.ttf", format: "truetype", weight: "700" },
  { family: "Yoe Yar One Light", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/YoeYarOne/YoeYar-One%20Light.ttf", format: "truetype", weight: "400" },
  { family: "Yoe Yar One Regular", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/YoeYarOne/YoeYar-One%20Regular.ttf", format: "truetype", weight: "400" },
  { family: "Yunghkio", source: "/fonts/Myanmar-Unicode-Fonts-2025-1/Yunghkio/Yunghkio.ttf", format: "truetype", weight: "400" },
];

export const LOCAL_FONT_FAMILIES: string[] = [
  "Cherry Unicode",
  "Gantgaw Regular",
  "Jasmine Unicode",
  "KT 02",
  "KT 03",
  "Masterpiece Uni Round",
  "MON3Anonta1",
  "mm3 05 Jan 2011",
  "mm3h",
  "mm3 multi os",
  "mm3sh",
  "MM3 Paoh",
  "Myanmar Angoun",
  "Myanmar Black",
  "myanmarcensus",
  "Myanmar Gant Gaw",
  "Myanmar Khway",
  "Myanmar Kuttar",
  "Myanmar Nayone",
  "Myanmar Njaun",
  "Myanmar Pa Oh One",
  "MIUI Unicode",
  "Myanmar Pauklay",
  "Myanmar Phetsot",
  "Myanmar Pixel Smooth",
  "Myanmar Pixel",
  "Myanmar Ponenyet",
  "Myanmar Punk",
  "Myanmar Rosemarry",
  "Myanmar Sabae",
  "Myanmar Sagar",
  "Myanmar Sans Pro",
  "Myanmar Square Light",
  "Myanmar Square",
  "Myanmar Tagu",
  "Myanmar Taungyi",
  "Myanmar Text Melano",
  "mmrtextb",
  "mmrtext",
  "Myanmar Thuriya",
  "Myanmar Thuriya volt",
  "Myanmar Yinmar",
  "Nam Khone Unicode",
  "Namkhon Web pro",
  "NK Grand",
  "NK SSmart2",
  "NK SSmart3",
  "NK SSmart4",
  "Notosan Myanmar UI Bold",
  "Noto Sans Myanmar Bold",
  "Noto Sans Myanmar Regular",
  "Noto Sans Myanmar UI Bold",
  "Noto Sans Myanmar UI Regular",
  "Padauk GhostтАЛ",
  "Padauk Grand Pro v2",
  "Padauk Kyaungchikote",
  "Padauk bold",
  "padauk bookbold",
  "padauk book",
  "Padauk",
  "Padauk Zawgyi",
  "Padauk Sagar",
  "Padauk Sgaw Bold",
  "Padauk Sgaw bookbold",
  "Padauk Sgaw book",
  "Padauk Sgaw",
  "Pang Long 2011feb7",
  "Paoh Dragon App",
  "Parabaik20080421",
  "Parabaik UTN11 3",
  "pyidaungsu 1.2",
  "pyidaungsu 1.3",
  "pyidaungsu",
  "Samsung Myanmar",
  "Shan Unicode",
  "Than Lwin",
  "Thar Lon",
  "Win Uni Innwa",
  "Yoe Yar One Bold",
  "Yoe Yar One Light",
  "Yoe Yar One Regular",
  "Yunghkio",
];
